export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FILTER_BY_COUNTRY = 'FILTER_BY_COUNTRY';
export const FILTER_BY_REGION = 'FILTER_BY_REGION';
export const CHANGE_COUNTRIES = 'CHANGE_COUNTRIES';
